version: '3'
services:
  database:
    container_name: database
    image: 'mysql:5.7.16'
    volumes:
      - './.data/db:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_DATABASE: 'os_moderator'
      MYSQL_USER: 'os_moderator'
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - '3306:3306'
  redis:
    container_name: redis
    image: 'redis:3.2.1'
    ports:
      - '6379:6379'
  web:
    build:
      context: ../..
      dockerfile: "deployments/local/Dockerfile"
    environment:
      IMAGE_FLAVOR: 'web'
      MODERATOR_FLAVOR: "${MODERATOR_FLAVOR}"
      DATABASE_HOST: database
      DATABASE_NAME: 'os_moderator'
      DATABASE_USER: 'os_moderator'
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      REDIS_URL: 'redis://redis:6379'
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      HTTPS_LINKS_ONLY: 'false'
      APP_NAME: 'Moderator'
      REDIRECT_OAUTH_TO: 'frontend_url'
      GOOGLE_CLOUD_API_KEY: "${GOOGLE_CLOUD_API_KEY}"
      PORT: 8000
    ports:
      - "8000:8000"
    links:
        - database
        - redis
  processing:
    build:
      context: ../..
      dockerfile: "deployments/local/Dockerfile"
    environment:
      IMAGE_FLAVOR: 'processing'
      MODERATOR_FLAVOR: "${MODERATOR_FLAVOR}"
      DATABASE_HOST: database
      DATABASE_NAME: 'os_moderator'
      DATABASE_USER: 'os_moderator'
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      REDIS_URL: 'redis://redis:6379'
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      GOOGLE_CLOUD_API_KEY: "${GOOGLE_CLOUD_API_KEY}"
    links:
        - database
        - redis
